runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /cerveza/
  static_files: cerveza/index.html
  upload: cerveza/index.html  

- url: /cerveza
  static_files: cerveza/index.html
  upload: cerveza/index.html    

- url: /cerveza/contado/
  static_files: cerveza/contado/index.html
  upload: cerveza/contado/index.html  

- url: /cerveza/contado
  static_files: cerveza/contado/index.html
  upload: cerveza/contado/index.html      

- url: /cerveza/consignacion/
  static_files: cerveza/consignacion/index.html
  upload: cerveza/consignacion/index.html 

- url: /cerveza/consignacion
  static_files: cerveza/consignacion/index.html
  upload: cerveza/consignacion/index.html   

- url: /alquiler/
  static_files: alquiler/index.html
  upload: alquiler/index.html

- url: /alquiler
  static_files: alquiler/index.html
  upload: alquiler/index.html     

- url: /alquiler/sillas/
  static_files: alquiler/sillas/alquiler-sillas.html
  upload: alquiler/sillas/alquiler-sillas.html 

- url: /alquiler/sillas
  static_files: alquiler/sillas/alquiler-sillas.html
  upload: alquiler/sillas/alquiler-sillas.html 

- url: /alquiler/mesas/
  static_files: alquiler/mesas/alquiler-mesas.html
  upload: alquiler/mesas/alquiler-mesas.html  

- url: /alquiler/mesas
  static_files: alquiler/mesas/alquiler-mesas.html
  upload: alquiler/mesas/alquiler-mesas.html  

- url: /alquiler/chanchas/
  static_files: alquiler/chanchas/alquiler-chanchas.html
  upload: alquiler/chanchas/alquiler-chanchas.html 

- url: /alquiler/chanchas
  static_files: alquiler/chanchas/alquiler-chanchas.html
  upload: alquiler/chanchas/alquiler-chanchas.html 

- url: /(.*)
  static_files: \1
  upload: (.*)
